import type { PageName } from '@/lib/store'

// Maps the legacy PageName identifiers used by menu items, search results,
// notifications, and dashboard quick-action buttons to real Next.js URLs.
// Every PageName is now backed by a real route (phases 1–3 shipped 2026-05-26).
export const MIGRATED_PAGES: Partial<Record<PageName, (...args: string[]) => string>> = {
  'dashboard': () => '/dashboard',
  'students': () => '/students',
  'student-houses': () => '/students/houses',
  'student-detail': (id?: string) => (id ? `/students/${id}` : '/students'),
  'edit-student': (id?: string) => (id ? `/students/${id}/edit` : '/students'),
  'admission-form': () => '/students/admit',
  'bulk-admission': () => '/students/admit/bulk',
  'alumni': () => '/students/alumni',
  'attendance': () => '/attendance/mark',
  'mark-attendance': () => '/attendance/mark',
  'view-attendance': () => '/attendance/view',
  'employee-attendance': () => '/attendance/staff',
  'attendance-audit-log': () => '/audit-logs/attendance',
  'attendance-reports': () => '/attendance/reports',
  'attendance-kiosk': () => '/attendance/kiosk',
  'attendance-credentials': () => '/attendance/credentials',
  'rfid-card-assign': () => '/attendance/cards',
  'rfid-devices': () => '/attendance/devices',
  'rfid-audit': () => '/audit-logs/rfid',
  'student-rfid-cards': (id?: string) => (id ? `/students/${id}/cards` : '/students'),
  'my-attendance': () => '/attendance/me',
  'fees-heads': () => '/fees/heads',
  'fees-groups': () => '/fees/groups',
  'fees-structures': () => '/fees/structures',
  'fee-collections': (id?: string) => (id ? `/fees/collections?preselect=${id}` : '/fees/collections'),
  'fee-details': () => '/fees/collections',
  'fee-change-group': () => '/fees/change-group',
  'fee-demand-config': () => '/settings/fee-demand-config',
  'fee-demand-slips': () => '/fees/demand-slips',
  'fee-audit-log': () => '/audit-logs/fees',
  'fee-reports': () => '/fees/reports',
  'fee-list': () => '/fees/list',
  'classes': () => '/academics/classes',
  'my-classes': () => '/academics/my-classes',
  'add-class': () => '/academics/classes/new',
  'edit-class': (id?: string) => (id ? `/academics/classes/${id}/edit` : '/academics/classes'),
  'subjects': () => '/academics/subjects',
  'add-subject': () => '/academics/subjects/new',
  'edit-subject': (id?: string) => (id ? `/academics/subjects/${id}/edit` : '/academics/subjects'),
  'timetable': () => '/academics/timetable',
  'promote-student': () => '/academics/promote',
  'assign-roll-numbers': () => '/academics/assign-rolls',
  'academic-years': () => '/academics/years',
  'holidays': () => '/academics/years/holidays',
  'teachers': () => '/teachers',
  'add-teacher': () => '/teachers/new',
  'parents': () => '/parents',
  'my-children': () => '/parents',
  // Parent portal (backed by /api/parent/*). Distinct keys so they don't collide
  // with the admin pages that reuse `fee-details` / `my-attendance`.
  'parent-children': () => '/my-children',
  'parent-fees': (id?: string) => (id ? `/my-children/fees?studentId=${id}` : '/my-children/fees'),
  'parent-attendance': (id?: string) => (id ? `/my-children/attendance?studentId=${id}` : '/my-children/attendance'),
  'parent-exams': (id?: string) => (id ? `/my-children/exams?studentId=${id}` : '/my-children/exams'),
  'staff': () => '/staff',
  'staff-create': () => '/staff/new',
  'staff-detail': (id?: string) => (id ? `/staff/${id}` : '/staff'),
  'transport': () => '/transport/routes',
  'add-transport-route': () => '/transport/routes/new',
  'edit-transport-route': (id?: string) => (id ? `/transport/routes/${id}/edit` : '/transport/routes'),
  'transport-annual-setup': () => '/transport/annual-setup',
  'drivers': () => '/transport/drivers',
  'add-driver': () => '/transport/drivers/new',
  'hostel': () => '/hostel/hostels',
  'add-hostel': () => '/hostel/hostels/new',
  'edit-hostel': (id?: string) => (id ? `/hostel/hostels/${id}/edit` : '/hostel/hostels'),
  'hostel-annual-setup': () => '/hostel/annual-setup',
  'exams': () => '/exams',
  'exam-results': () => '/exams/results',
  // Exam Module (Phase 1 wires URL stubs; pages land in Phase 2+).
  'exam-dashboard': () => '/exams',
  'exam-paradigms': () => '/exams/paradigms',
  'exam-paradigm-edit': (id?: string) => (id ? `/exams/paradigms/${id}/edit` : '/exams/paradigms'),
  'exam-groups': (paradigmId?: string) => (paradigmId ? `/exams/paradigms/${paradigmId}/groups` : '/exams/paradigms'),
  'exam-list': () => '/exams/list',
  'exam-create': () => '/exams/new',
  'exam-edit': (id?: string) => (id ? `/exams/${id}/edit` : '/exams/list'),
  'exam-configure': (id?: string) => (id ? `/exams/${id}/configure` : '/exams/list'),
  'exam-schedule': (id?: string) => (id ? `/exams/${id}/schedule` : '/exams/list'),
  'exam-marks-entry': (id?: string) => (id ? `/exams/${id}/marks` : '/exams/list'),
  'exam-grade-scales': () => '/exams/grade-scales',
  'exam-grade-scale-edit': (id?: string) => (id ? `/exams/grade-scales/${id}/edit` : '/exams/grade-scales'),
  'exam-result-preview': (id?: string) => (id ? `/exams/${id}/results` : '/exams/list'),
  'exam-published-results': () => '/exams/published',
  'exam-report-card-templates': () => '/exams/report-card-templates',
  'exam-report-card-template-edit': (id?: string) => (id ? `/exams/report-card-templates/${id}/edit` : '/exams/report-card-templates'),
  'exam-audit-log': () => '/audit-logs/exams',
  'teacher-subject-assignments': () => '/settings/teacher-subjects',
  'student-subject-mappings': () => '/academics/student-subjects',
  'library': () => '/library',
  'inventory': () => '/inventory',
  'inventory-sell': () => '/inventory/sell',
  'inventory-sales': () => '/inventory/sales',
  'inventory-catalog': () => '/inventory/catalog',
  'inventory-reports': () => '/inventory/reports',
  'salary': () => '/salary/structure',
  'salary-structure': () => '/salary/structure',
  'salary-payments': () => '/salary/payments',
  'salary-advance': () => '/salary/advance',
  'notifications': () => '/notifications',
  'announcements': () => '/announcements',
  'support': () => '/support',
  'settings': () => '/settings',
  'school-roles': () => '/settings/roles',
  'school-permissions': () => '/settings/permissions',
  'school-users': () => '/settings/users',
  'super-admin-permissions': () => '/super-admin/permissions',
  'super-admin-roles': () => '/super-admin/roles',
  'platform-announcements': () => '/super-admin/announcements',
  'tenant-exports': () => '/super-admin/exports',
  'platform-branding': () => '/super-admin/branding',
  'schools': () => '/admin/schools',
  'add-school': () => '/admin/schools/new',
  'edit-school': (id?: string) => (id ? `/admin/schools/${id}/edit` : '/admin/schools'),
  'school-detail': (id?: string) => (id ? `/admin/schools/${id}` : '/admin/schools'),
  'contact-requests': () => '/marketing/contact-requests',
  'testimonials': () => '/marketing/testimonials',
  'pricing-plans': () => '/marketing/pricing-plans',
  'team-members': () => '/marketing/team-members',
  'id-cards': () => '/id-cards',
  'id-card-templates': () => '/id-cards/templates',
  'id-card-template-new': () => '/id-cards/templates/new',
  'id-card-template-edit': (id?: string) => (id ? `/id-cards/templates/${id}` : '/id-cards/templates'),
  'id-card-generate': () => '/id-cards/generate',
  'id-card-showcase': () => '/id-cards/showcase',
}

export function resolveMigratedUrl(page: PageName, id?: string): string | null {
  const resolver = MIGRATED_PAGES[page]
  if (!resolver) return null
  return resolver(id ?? '')
}
