import type { PageName } from '@/lib/store'

// Maps the legacy PageName identifiers used by menu items, search results,
// notifications, and dashboard quick-action buttons to real Next.js URLs.
// Every PageName is now backed by a real route (phases 1–3 shipped 2026-05-26).
export const MIGRATED_PAGES: Partial<Record<PageName, (...args: string[]) => string>> = {
  'dashboard': () => '/dashboard',
  'students': () => '/students',
  'student-detail': (id?: string) => (id ? `/students/${id}` : '/students'),
  'edit-student': (id?: string) => (id ? `/students/${id}/edit` : '/students'),
  'admission-form': () => '/students/admit',
  'bulk-admission': () => '/students/admit/bulk',
  'attendance': () => '/attendance/mark',
  'mark-attendance': () => '/attendance/mark',
  'view-attendance': () => '/attendance/view',
  'attendance-audit-log': () => '/audit-logs/attendance',
  'attendance-reports': () => '/attendance/reports',
  'my-attendance': () => '/attendance/me',
  'fees-heads': () => '/fees/heads',
  'fees-groups': () => '/fees/groups',
  'fees-structures': () => '/fees/structures',
  'fee-collections': (id?: string) => (id ? `/fees/collections?preselect=${id}` : '/fees/collections'),
  'fee-details': () => '/fees/collections',
  'fee-change-group': () => '/fees/change-group',
  'classes': () => '/academics/classes',
  'my-classes': () => '/academics/my-classes',
  'add-class': () => '/academics/classes/new',
  'edit-class': (id?: string) => (id ? `/academics/classes/${id}/edit` : '/academics/classes'),
  'subjects': () => '/academics/subjects',
  'add-subject': () => '/academics/subjects/new',
  'edit-subject': (id?: string) => (id ? `/academics/subjects/${id}/edit` : '/academics/subjects'),
  'timetable': () => '/academics/timetable',
  'promote-student': () => '/academics/promote',
  'assign-roll-numbers': () => '/academics/assign-rolls',
  'academic-years': () => '/academics/years',
  'teachers': () => '/teachers',
  'add-teacher': () => '/teachers/new',
  'parents': () => '/parents',
  'my-children': () => '/parents',
  'staff': () => '/staff',
  'staff-create': () => '/staff/new',
  'staff-detail': (id?: string) => (id ? `/staff/${id}` : '/staff'),
  'transport': () => '/transport/routes',
  'add-transport-route': () => '/transport/routes/new',
  'edit-transport-route': (id?: string) => (id ? `/transport/routes/${id}/edit` : '/transport/routes'),
  'transport-annual-setup': () => '/transport/annual-setup',
  'drivers': () => '/transport/drivers',
  'add-driver': () => '/transport/drivers/new',
  'exams': () => '/exams',
  'exam-results': () => '/exams/results',
  'library': () => '/library',
  'inventory': () => '/inventory',
  'petty-cash': () => '/petty-cash',
  'salary': () => '/salary/structure',
  'salary-structure': () => '/salary/structure',
  'salary-payments': () => '/salary/payments',
  'salary-advance': () => '/salary/advance',
  'notifications': () => '/notifications',
  'announcements': () => '/announcements',
  'support': () => '/support',
  'settings': () => '/settings',
  'school-roles': () => '/settings/roles',
  'school-permissions': () => '/settings/permissions',
  'school-users': () => '/settings/users',
  'super-admin-permissions': () => '/super-admin/permissions',
  'super-admin-roles': () => '/super-admin/roles',
  'schools': () => '/admin/schools',
  'add-school': () => '/admin/schools/new',
  'edit-school': (id?: string) => (id ? `/admin/schools/${id}/edit` : '/admin/schools'),
  'school-detail': (id?: string) => (id ? `/admin/schools/${id}` : '/admin/schools'),
  'contact-requests': () => '/marketing/contact-requests',
  'testimonials': () => '/marketing/testimonials',
  'pricing-plans': () => '/marketing/pricing-plans',
  'team-members': () => '/marketing/team-members',
}

export function resolveMigratedUrl(page: PageName, id?: string): string | null {
  const resolver = MIGRATED_PAGES[page]
  if (!resolver) return null
  return resolver(id ?? '')
}
